on:
  push:
    branches:
      - add-new-contributor-reminder

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to find if a commitor is new to contribute.
    steps:
      - name: First Contribution Check
        uses: sukki37/first-contribution-check-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Output of Previous Step
        run: |
          echo 'first-check output is ${{ steps.first-check.outputs.isNewContributor }}'
